// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADf43P0Qoq5odnYeVRLkm4WRhdcsEu7MY',
    appId: '1:1010597562204:web:5ab0d34f18e8f019d62399',
    messagingSenderId: '1010597562204',
    projectId: 'qlvlxd-e5fbd',
    authDomain: 'qlvlxd-e5fbd.firebaseapp.com',
    storageBucket: 'qlvlxd-e5fbd.firebasestorage.app',
    measurementId: 'G-NF1PZEWFN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvuiO_Kac0d9UkNtkGj0y1FfUF8lxLNbs',
    appId: '1:1010597562204:android:96d2e3a54405aec4d62399',
    messagingSenderId: '1010597562204',
    projectId: 'qlvlxd-e5fbd',
    storageBucket: 'qlvlxd-e5fbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5qR4u1YbMNh9JDWbgNp833kM88647JQs',
    appId: '1:1010597562204:ios:3d9aea917d856d13d62399',
    messagingSenderId: '1010597562204',
    projectId: 'qlvlxd-e5fbd',
    storageBucket: 'qlvlxd-e5fbd.firebasestorage.app',
    iosBundleId: 'com.example.quanlyvlxd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5qR4u1YbMNh9JDWbgNp833kM88647JQs',
    appId: '1:1010597562204:ios:3d9aea917d856d13d62399',
    messagingSenderId: '1010597562204',
    projectId: 'qlvlxd-e5fbd',
    storageBucket: 'qlvlxd-e5fbd.firebasestorage.app',
    iosBundleId: 'com.example.quanlyvlxd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADf43P0Qoq5odnYeVRLkm4WRhdcsEu7MY',
    appId: '1:1010597562204:web:20c2dc41ca397dbad62399',
    messagingSenderId: '1010597562204',
    projectId: 'qlvlxd-e5fbd',
    authDomain: 'qlvlxd-e5fbd.firebaseapp.com',
    storageBucket: 'qlvlxd-e5fbd.firebasestorage.app',
    measurementId: 'G-B5B1T29LLE',
  );
}
